About
womenwhocoderecife/micropigmentacao-solidaria pull request #16
Opened 2019-11-28 22:42 UTC by cecivieira

2019-12-07 14:37 UTC, talitaoliveira requested changes
Remover o import de fonte do CSS e colocar no `header` index.html usando o tipo de importação para HTML que aparece no Google Fonts.

2019-12-07 14:38 UTC, talitaoliveira commented
**A fazer:**
- [ ] Remover a importação da fonte do CSS e colocar no header do index.html

**Sugestões:**

[ ] Iniciar o desenvolvimento seguindo o conceito de mobile first

2019-12-07 22:41 UTC, cecivieira commented
@talitaoliveira Alterações realizadas

2019-12-09 01:27 UTC, talitaoliveira approved these changes

2020-02-08 16:27 UTC, merged